### ISSUE TITLE
可见范围选项的交互

### ISSUE THREAD

**Issue by skyue** [lmm214/memos-bber#10]
我使用可见范围选项的频率挺高的，有两个问题：

1. 可见范围是个敏感选项，但现在的锁样式且不同状态都是灰色，有些弱。公开内容误发私密倒还好，但如果是私密内容误发公开就很尴尬。——觉得官方发布框以文字方式展示下拉觉得就挺强，但如果挨着发布按钮边上会更好。
2. 打开插件后第一次点击锁展开选项，很快就自动收起了。见动图。

![Feb-18-2023 13-51-14](https://user-images.githubusercontent.com/10450242/219843699-b8b21398-49cb-4034-bcd4-c14d8cd23ee1.gif)

**Comment by lmm214** [comment]
<img width="501" alt="iShot_2023-02-25_16 23 06" src="https://user-images.githubusercontent.com/1472390/221347078-00019907-6d08-4a04-816e-d08793589a4e.png">

嗯，已使用官方同样式
