### ISSUE TITLE
发布成功后，下面展示刚发布的memos，但如果有置顶，会一直展示置顶的。

### ISSUE THREAD

**Issue by skyue** [lmm214/memos-bber#12]
如图，下面是我一个月前置顶的内容。可以考虑把置顶内容过滤掉。

<img width="522" alt="image" src="https://user-images.githubusercontent.com/10450242/224233586-a9717b50-4950-41d4-982c-8d926fd9e425.png">

**Comment by lmm214** [comment]
2023.03.10 已修复。之前是调用最新一条，现在是直接调用刚发布的 memoID
