### ISSUE TITLE
2023.03.09 新增右键发送文本至 Memos 输入框。 的建议

### ISSUE THREAD

**Issue by iTigerz** [lmm214/memos-bber#13]
1. 能否加个开关，就是右键直接发送，直接 “记下”，不必再点下toolbar的icon，再点“记下”
2. 在不点开 icon 的情况下，可以直接 右键 追加内容 到输入框，而不是这一次覆盖上一次的。

以上，变成 开关，让使用者 选择为好

现在发送到会吞掉换行符，希望能保留。

谢谢。

**Comment by lmm214** [comment]
临时给扩展加个快捷键吧，手动复制粘贴一下，最后 ctrl enter 记下。

**Comment by skyue** [comment]
> 以上，变成 开关，让使用者 选择为好
> 
> 现在发送到会吞掉换行符，希望能保留。

特意来试了下这个功能，很好用。也提个小想法：

看一篇长文的时候，经常会有好几个片段想保存下来，右键发送的时候，可以不要覆盖前面的文本，而用追加模式。这样同一个文章的多段内容，能在一个memo中发布。做摘录很实用。

**Comment by lmm214** [comment]
选中文本扩展收到的只是纯文本，不包含换行符。2023.03.25 版本新增了一个临时变量，在当前所有打开页面为未刷新，会“追加”。
