### ISSUE TITLE
上传图片重命名追加的时间后缀只到分钟，使用图床时，连续上传多张图片分钟间隔不够用，会被覆盖。

### ISSUE THREAD

**Issue by skyue** [lmm214/memos-bber#15]
建议到秒，一条memo中一分钟内上传多张图片还是挺常见的。

**Comment by lmm214** [comment]
2023.03.19 上传图片重命名精确的秒；打开插件时 focus 输入框（配合右键发送文本到扩展，设置快捷键打开扩展，按下 Ctrl+Enter 记下）。
