### ISSUE TITLE
有字数限制吗？

### ISSUE THREAD

**Issue by salviox** [lmm214/memos-bber#16]
为什么同一个网页，发送多次后，前面的文字消失了。
这个BUG能修复吗？

**Comment by lmm214** [comment]
打开的所有 tabs 不能刷新，因为内容是存在临时变量里的。

**Comment by salviox** [comment]
同一个tab，没有刷新，可能出现两种BUG：
1. 文字多的时候，发送不过去，内容没有改变。
2. 可以发送过去，但是前面已经发送的内容被清除掉了。
想复现的话，找一个文字多的页面，多发送几遍就可以看到了
希望能修复
