### ISSUE TITLE
功能请求：一键清空输入框的按钮

### ISSUE THREAD

**Issue by EZForever** [lmm214/memos-bber#18]
目前如果不想要现有的记录内容（可能是划词划错了或者怎么样），则只能在打开Memos弹窗后手动全选删除。（当然可以用快捷键Ctrl-A再Delete，不过如果是用鼠标点开的弹窗，操作会繁琐一点。）给输入框加一个清空按钮，类似于各大网站搜索框最后的叉号，会是一个不错的功能，而且对现有功能也基本不会造成影响。

**Comment by lmm214** [comment]
右键发送为临时变量，可以直接刷新任何页面会清空。

**Comment by EZForever** [comment]
经过实际测试，这样依赖于特定程序行为的功能实现对用户体验比不友好且会造成内部状态的错乱（background里的`tempCont` vs. `storage.sync`），而且鉴于Memos输入框是独立于各个标签页存在的，允许任意标签页发送文本清空整个输入框应被视为bug而非特性（参见#16）。

**Comment by lmm214** [comment]
的确是 hack，以合并 pr 感谢
