### ISSUE TITLE
Edge安装插件填写API后，发送消息是提示网络问题发送失败？

### ISSUE THREAD

**Issue by quickflash2** [lmm214/memos-bber#3]
Edge安装插件填写API后，发送消息提示网络问题发送失败？无论本地和网址均失败

**Comment by ArslanTu** [comment]
![image](https://user-images.githubusercontent.com/61570284/200152559-dd31fc51-c950-4b55-86de-8a459311589d.png)
可见性设置了吗？我一开始也失败，选了可见性就好了。

**Comment by quickflash2** [comment]
谢谢，我才发现



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月06日 11:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lmm214/memos-bber] Edge安装插件填写API后，发送消息是提示网络问题发送失败？ (Issue #3) |


可见性设置了吗？我一开始也失败，选了可见性就好了。

**Comment by lmm214** [comment]
已修复。
