### ISSUE TITLE
因为网址的格式折腾了半天，给其他用户提个醒

### ISSUE THREAD

**Issue by Elliont** [lmm214/memos-bber#30]
格式： http://xxx.xxx.com:1234/
切记最后要加斜杠，不然怎么都连不上服务器

**Comment by AzureWindRises** [comment]
找了好久的问题一直解决不了，翻到这才看到答案

**Comment by CLKRUN** [comment]
浏览器插件中的提示会有所帮助。

**Comment by qianhd** [comment]
原来如此，感谢

**Comment by signup2k** [comment]
感谢！不管带不带端口号，都要记得加斜杠...

**Comment by slyang40** [comment]
请问大佬们现在chrome和firefox的插件还能工作吗?输入服务器地址和access token无法发送消息
