### ISSUE TITLE
已经不支持v0.22.0的Memos

### ISSUE THREAD

**Issue by jxzzlfh** [lmm214/memos-bber#38]
已经不支持v0.22.0的Memos

**Comment by jiangnilnil** [comment]
0.22  api/v1/memo  update to api/v1/memos

https://memos.apidocumentation.com/reference#tag/memoservice/post/api/v1/memos

**Comment by lmm214** [comment]
试试这个版本
https://github.com/lmm214/memos-bber/releases/tag/2024.07.21
