### ISSUE TITLE
是否有可能改造为嵌入网页的popup按钮？

### ISSUE THREAD

**Issue by toyqiu** [lmm214/memos-bber#4]
因为是多台不同电脑切换，远程办公，我自己日常是一开一个自定义的导航页【php】，看到 languages 显示 JavaScript
42.3%   HTML  37.7%    CSS 20.0%  ，想请教一下能否把这个 chrome插件改造成为嵌入网页的popup按钮？敬请不吝赐教，感谢!

![图像 1](https://user-images.githubusercontent.com/479873/201465588-2232be0a-46d1-4994-9645-473067f0adad.png)

**Comment by lmm214** [comment]
https://edui123.com/memos/ 

是这样吗？

**Comment by lmm214** [comment]
https://github.com/lmm214/memos-web

**Comment by toyqiu** [comment]
> https://github.com/lmm214/memos-web

![01](https://user-images.githubusercontent.com/479873/201722124-a5889248-c659-497e-a9bf-05eebb8870af.png)
![02](https://user-images.githubusercontent.com/479873/201722155-199ce978-f167-4e74-8459-8748e90f22bb.png)
