### ISSUE TITLE
新版本还是不支持v0.22.0的Memos，除了发布功能能用，标签获取/图片上传/搜索/随机都不行

### ISSUE THREAD

**Issue by ly0813** [lmm214/memos-bber#41]
除了发布功能能用，标签获取/图片上传/搜索/随机都不行
烦请作者看下api调用，更新下，谢谢，https://memos.apidocumentation.com/reference#tag/memoservice/post/api/v1/memos
![image](https://github.com/lmm214/memos-bber/assets/53300199/a6bc84d4-2949-4815-bd6d-aa9b2f5c291c)

**Comment by lmm214** [comment]
试试这个版本
https://github.com/lmm214/memos-bber/releases/tag/2024.07.21
