### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by erduo77** [lmm214/memos-bber#46]
<img width="508" alt="image" src="https://github.com/lmm214/memos-bber/assets/144216104/c058df43-53a4-4d60-8985-ec367357f0dd">
之前用的好好的，后面发现插件就这样用不了了，token 换过没有用

**Comment by slyang40** [comment]
我也有类似错误，或者发送失败

**Comment by erduo77** [comment]
> 你的版本是什么？

Version: v0.21.0

**Comment by lmm214** [comment]
22 之前的用这个版本
https://github.com/lmm214/memos-bber/releases/tag/2023.09.19

**Comment by slyang40** [comment]
@lmm214 大佬能不能帮忙更新一下firefox的插件呀
