### ISSUE TITLE
What version(s) does this support? It doesn't seem to be backward compatible

### ISSUE THREAD

**Issue by HappyZ** [lmm214/memos-bber#48]
Mine is still on v0.21.0.

And https://github.com/lmm214/memos-bber/blame/e292c83d36fbac0fd8b5a63e1b6f93f5368da6db/js/oper.js#L248 manually curl gives 404 not found.

It would be good to have a version check and advertise as single latest version support?

The current docker stable image points at v0.21.0.

**Comment by HappyZ** [comment]
never mind, apparently the stable release is built based on latest release and mine didn't notify the update correctly.

I upgraded to v0.22.3 and it works now.

The question still remains

**Comment by lmm214** [comment]
v0.22.3 is ok
