### ISSUE TITLE
谷歌应用商店似乎失效了？

### ISSUE THREAD

**Issue by linlord** [lmm214/memos-bber#49]
打开Chrome 应用商店：https://chrome.google.com/webstore/detail/memos-bber/cbhjebjfccgchgbmfbobjmebjjckgofe/后，会跳转回首页

**Comment by dryyun** [comment]
https://chrome.google.com/webstore/detail/memos-bber/cbhjebjfccgchgbmfbobjmebjjckgofe

**Comment by linlord** [comment]
> https://chrome.google.com/webstore/detail/memos-bber/cbhjebjfccgchgbmfbobjmebjjckgofe

Thanks!
