### ISSUE TITLE
希望到Edge 扩展库发布一下这个插件。

### ISSUE THREAD

**Issue by lhuanyun** [lmm214/memos-bber#6]
插件很棒。
为了方便同步，已经使用edge替换掉chrome

---

edge使用chrome插件库的插件，新登陆设备的edge没办法自动啦取插件，
需要自己手动到chrome商店里下载，有点儿麻烦。
希望作者发布一下edge商店里的memos-bber

---

感谢作者，提供这么好的插件，给memos带来了良好的体验！

**Comment by lmm214** [comment]
个人注册开发者，一直卡申请页面，等好心人转制
